# Generated by Django 5.0.1 on 2025-10-20 16:13

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("EOI", "Expression of Interest"), ("BOOKED", "Booked"), ("CANCELLED", "Cancelled")],
                        default="EOI",
                        max_length=10,
                    ),
                ),
                ("payment_note", models.TextField(blank=True, null=True)),
                ("ticket_number", models.CharField(blank=True, max_length=32, null=True)),
                ("room_assignment", models.CharField(blank=True, max_length=64, null=True)),
                ("special_needs", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="bookings", to="trips.trippackage"
                    ),
                ),
                (
                    "pilgrim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="accounts.pilgrimprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
            },
        ),
        migrations.CreateModel(
            name="HistoricalBooking",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("EOI", "Expression of Interest"), ("BOOKED", "Booked"), ("CANCELLED", "Cancelled")],
                        default="EOI",
                        max_length=10,
                    ),
                ),
                ("payment_note", models.TextField(blank=True, null=True)),
                ("ticket_number", models.CharField(blank=True, max_length=32, null=True)),
                ("room_assignment", models.CharField(blank=True, max_length=64, null=True)),
                ("special_needs", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trips.trippackage",
                    ),
                ),
                (
                    "pilgrim",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.pilgrimprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Booking",
                "verbose_name_plural": "historical Bookings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("pilgrim", "package"),
                name="unique_active_booking_per_package",
            ),
        ),
    ]
