# Generated by Django 5.0.1 on 2025-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="amount_paid_minor_units",
            field=models.IntegerField(default=0, help_text="Amount in smallest currency unit (e.g., cents)"),
        ),
        migrations.AddField(
            model_name="booking",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal staff notes", null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partial Payment"),
                    ("PAID", "Fully Paid"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="amount_paid_minor_units",
            field=models.IntegerField(default=0, help_text="Amount in smallest currency unit (e.g., cents)"),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal staff notes", null=True),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partial Payment"),
                    ("PAID", "Fully Paid"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="reference_number",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("EOI", "Expression of Interest"),
                    ("BOOKED", "Booked"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="EOI",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("EOI", "Expression of Interest"),
                    ("BOOKED", "Booked"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="EOI",
                max_length=10,
            ),
        ),
    ]
