# Generated by Django 5.0.1 on 2025-11-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpayment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Payment",
                "verbose_name_plural": "historical Payments",
            },
        ),
        migrations.AlterModelTable(
            name="historicalpayment",
            table=None,
        ),
    ]
