# Generated by Django 5.0.1 on 2025-11-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_historicalpayment_options_and_more"),
        ("common", "0001_initial"),
    ]

    operations = [
        # Rename existing currency column to currency (it's already a CharField)
        # This will map the currency_code model field to the existing currency db column
        migrations.RenameField(
            model_name="booking",
            old_name="currency",
            new_name="currency_code",
        ),
        # Add new FK field with different db column name
        migrations.AddField(
            model_name="booking",
            name="currency_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="common.currency",
            ),
        ),
        # Same for historicalbooking
        migrations.RenameField(
            model_name="historicalbooking",
            old_name="currency",
            new_name="currency_code",
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="currency_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.currency",
            ),
        ),
        # Same for payment
        migrations.RenameField(
            model_name="payment",
            old_name="currency",
            new_name="currency_code",
        ),
        migrations.AddField(
            model_name="payment",
            name="currency_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="common.currency",
            ),
        ),
        # Same for historicalpayment
        migrations.RenameField(
            model_name="historicalpayment",
            old_name="currency",
            new_name="currency_code",
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="currency_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.currency",
            ),
        ),
    ]
