# Generated by Django 5.0.1 on 2025-11-03 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(help_text="ISO 4217 currency code (e.g., USD, UGX)", max_length=3, unique=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Full currency name (e.g., US Dollar, Ugandan Shilling)", max_length=50),
                ),
                ("symbol", models.CharField(help_text="Currency symbol (e.g., $, USh)", max_length=10)),
                ("is_active", models.BooleanField(default=True, help_text="Whether this currency is currently in use")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currencies",
                "ordering": ["code"],
            },
        ),
    ]
