# Generated by Django 5.0.1 on 2025-11-03 15:51

from django.db import migrations


def populate_currencies(apps, schema_editor):
    """Populate the Currency table with common currencies."""
    Currency = apps.get_model('common', 'Currency')
    
    currencies = [
        {'code': 'USD', 'name': 'US Dollar', 'symbol': '$', 'is_active': True},
        {'code': 'UGX', 'name': 'Ugandan Shilling', 'symbol': 'USh', 'is_active': True},
        {'code': 'KES', 'name': 'Kenyan Shilling', 'symbol': 'KSh', 'is_active': True},
        {'code': 'TZS', 'name': 'Tanzanian Shilling', 'symbol': 'TSh', 'is_active': True},
        {'code': 'GBP', 'name': 'British Pound', 'symbol': '£', 'is_active': True},
        {'code': 'EUR', 'name': 'Euro', 'symbol': '€', 'is_active': True},
        {'code': 'SAR', 'name': 'Saudi Riyal', 'symbol': 'SR', 'is_active': True},
    ]
    
    for currency_data in currencies:
        Currency.objects.get_or_create(
            code=currency_data['code'],
            defaults={
                'name': currency_data['name'],
                'symbol': currency_data['symbol'],
                'is_active': currency_data['is_active'],
            }
        )


def migrate_package_currencies(apps, schema_editor):
    """Migrate existing package currency codes to Currency foreign keys."""
    TripPackage = apps.get_model('trips', 'TripPackage')
    Currency = apps.get_model('common', 'Currency')
    
    # Get all packages with currency_code
    packages = TripPackage.objects.exclude(currency_code__isnull=True).exclude(currency_code='')
    
    for package in packages:
        try:
            currency = Currency.objects.get(code=package.currency_code)
            package.currency_fk = currency
            package.save(update_fields=['currency_fk'])
        except Currency.DoesNotExist:
            # If currency doesn't exist, log it but continue
            print(f"Warning: Currency {package.currency_code} not found for package {package.id}")


def migrate_booking_currencies(apps, schema_editor):
    """Migrate existing booking currency codes to Currency foreign keys."""
    Booking = apps.get_model('bookings', 'Booking')
    Currency = apps.get_model('common', 'Currency')
    
    # Get all bookings with currency_code
    bookings = Booking.objects.exclude(currency_code__isnull=True).exclude(currency_code='')
    
    for booking in bookings:
        try:
            currency = Currency.objects.get(code=booking.currency_code)
            booking.currency_fk = currency
            booking.save(update_fields=['currency_fk'])
        except Currency.DoesNotExist:
            # Default to USD if currency not found
            try:
                currency = Currency.objects.get(code='USD')
                booking.currency_fk = currency
                booking.save(update_fields=['currency_fk'])
            except Currency.DoesNotExist:
                print(f"Warning: Could not set currency for booking {booking.id}")


def migrate_payment_currencies(apps, schema_editor):
    """Migrate existing payment currency codes to Currency foreign keys."""
    Payment = apps.get_model('bookings', 'Payment')
    Currency = apps.get_model('common', 'Currency')
    
    # Get all payments with currency_code
    payments = Payment.objects.exclude(currency_code__isnull=True).exclude(currency_code='')
    
    for payment in payments:
        try:
            currency = Currency.objects.get(code=payment.currency_code)
            payment.currency_fk = currency
            payment.save(update_fields=['currency_fk'])
        except Currency.DoesNotExist:
            # Default to USD if currency not found
            try:
                currency = Currency.objects.get(code='USD')
                payment.currency_fk = currency
                payment.save(update_fields=['currency_fk'])
            except Currency.DoesNotExist:
                print(f"Warning: Could not set currency for payment {payment.id}")


def reverse_migration(apps, schema_editor):
    """Reverse the migration by clearing foreign keys."""
    TripPackage = apps.get_model('trips', 'TripPackage')
    Booking = apps.get_model('bookings', 'Booking')
    Payment = apps.get_model('bookings', 'Payment')
    Currency = apps.get_model('common', 'Currency')
    
    TripPackage.objects.all().update(currency_fk=None)
    Booking.objects.all().update(currency_fk=None)
    Payment.objects.all().update(currency_fk=None)
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("trips", "0003_historicaltrippackage_currency_code_and_more"),
        ("bookings", "0005_booking_currency_code_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_currencies, reverse_migration),
        migrations.RunPython(migrate_package_currencies, migrations.RunPython.noop),
        migrations.RunPython(migrate_booking_currencies, migrations.RunPython.noop),
        migrations.RunPython(migrate_payment_currencies, migrations.RunPython.noop),
    ]
