# Generated by Django 5.0.1 on 2026-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_populate_and_migrate_currencies"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", editable=False, max_length=32, unique=True)),
                ("otp_support_phone", models.CharField(blank=True, default="", max_length=24)),
                ("otp_support_whatsapp", models.CharField(blank=True, default="", max_length=24)),
                (
                    "otp_fallback_message",
                    models.CharField(
                        blank=True,
                        default="If your code does not arrive, wait a moment, try resending, or contact Al Hilal support.",
                        max_length=255,
                    ),
                ),
                ("youtube_channel_id", models.CharField(blank=True, default="", max_length=64)),
                ("youtube_playlist_id", models.CharField(blank=True, default="", max_length=64)),
                ("youtube_cache_payload", models.JSONField(blank=True, default=list)),
                ("youtube_cache_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
                "db_table": "platform_settings",
            },
        ),
    ]
