# Generated by Django 5.0.1 on 2026-04-02 21:30

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_pilgrim_identity_fields'),
        ('common', '0003_platformsettings'),
        ('trips', '0007_historicaltrip_commercial_month_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('interest_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('GUIDE_REQUEST', 'Guide Request')], max_length=20)),
                ('travel_window', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(max_length=64)),
                ('page_path', models.CharField(max_length=255)),
                ('context_label', models.CharField(max_length=120)),
                ('cta_label', models.CharField(max_length=120)),
                ('campaign', models.CharField(blank=True, default='', max_length=120)),
                ('referrer', models.URLField(blank=True, default='', max_length=500)),
                ('utm_source', models.CharField(blank=True, default='', max_length=120)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=120)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=120)),
                ('utm_content', models.CharField(blank=True, default='', max_length=120)),
                ('utm_term', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CLOSED', 'Closed')], default='NEW', max_length=16)),
                ('follow_up_notes', models.TextField(blank=True, default='')),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_website_leads', to='accounts.account')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_leads', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Website Lead',
                'verbose_name_plural': 'Website Leads',
                'db_table': 'website_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='websitelead',
            index=models.Index(fields=['status'], name='website_lea_status_3d9e46_idx'),
        ),
        migrations.AddIndex(
            model_name='websitelead',
            index=models.Index(fields=['interest_type'], name='website_lea_interes_8578f4_idx'),
        ),
        migrations.AddIndex(
            model_name='websitelead',
            index=models.Index(fields=['source'], name='website_lea_source_14b921_idx'),
        ),
        migrations.AddIndex(
            model_name='websitelead',
            index=models.Index(fields=['created_at'], name='website_lea_created_758526_idx'),
        ),
    ]
