# Generated by Django 5.0.1 on 2026-04-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_websitelead"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="lead_notification_cc_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="lead_notification_to_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="websitelead",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
    ]
