# Generated by Django 5.0.1 on 2026-04-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_platformsettings_lead_notification_and_websitelead_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="mobile_support_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="mobile_support_message",
            field=models.CharField(
                blank=True,
                default="Contact Al Hilal support if you need help with documents, readiness blockers, or in-trip updates.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="mobile_support_phone",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="mobile_support_whatsapp",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="notification_provider_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="notification_provider_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="notification_provider_notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
