# Generated by Django 5.0.1 on 2025-10-30 11:31

import apps.common.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilgrims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpassport",
            name="issue_country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="historicalpassport",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpassport",
            name="passport_no",
            field=apps.common.encryption.EncryptedCharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="historicalpassport",
            name="scanned_copy_public_id",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="historicalvisa",
            name="scanned_copy_public_id",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="historicalvisa",
            name="visa_no",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="passport",
            name="issue_country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="passport",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passport",
            name="passport_no",
            field=apps.common.encryption.EncryptedCharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="passport",
            name="scanned_copy_public_id",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="visa",
            name="scanned_copy_public_id",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="visa",
            name="visa_no",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
