# Generated by Django 5.0.1 on 2025-11-11 13:37

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_pilgrim_identity_fields"),
        ("bookings", "0006_remove_booking_currency_code_and_more"),
        ("pilgrims", "0002_historicalpassport_issue_country_and_more"),
        ("trips", "0005_add_featured_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvisa",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalvisa",
            name="pilgrim",
        ),
        migrations.RemoveField(
            model_name="historicalvisa",
            name="trip",
        ),
        migrations.RemoveField(
            model_name="passport",
            name="pilgrim",
        ),
        migrations.RemoveField(
            model_name="visa",
            name="pilgrim",
        ),
        migrations.RemoveField(
            model_name="visa",
            name="trip",
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passport"),
                            ("VISA", "Visa"),
                            ("VACCINATION", "Vaccination Certificate"),
                            ("ID_CARD", "ID Card"),
                            ("BIRTH_CERTIFICATE", "Birth Certificate"),
                            ("TRAVEL_PERMIT", "Travel Permit"),
                            ("OTHER", "Other Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="e.g., 'Passport - Uganda', 'Visa - Umrah 2025'", max_length=200)),
                (
                    "document_number",
                    models.CharField(
                        blank=True, help_text="Passport number, visa number, etc.", max_length=100, null=True
                    ),
                ),
                (
                    "issuing_country",
                    models.CharField(blank=True, help_text="ISO 2-letter country code", max_length=2, null=True),
                ),
                ("file_public_id", models.CharField(help_text="Cloudinary public ID", max_length=160)),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="Optional: Direct URL (auto-generated from public_id)", null=True
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending Review"), ("VERIFIED", "Verified"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Internal staff notes", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link document to a specific booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="bookings.booking",
                    ),
                ),
                (
                    "pilgrim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.pilgrimprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link document to a specific trip (e.g., for visas)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="trips.trip",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who uploaded (if admin upload)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDocument",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passport"),
                            ("VISA", "Visa"),
                            ("VACCINATION", "Vaccination Certificate"),
                            ("ID_CARD", "ID Card"),
                            ("BIRTH_CERTIFICATE", "Birth Certificate"),
                            ("TRAVEL_PERMIT", "Travel Permit"),
                            ("OTHER", "Other Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="e.g., 'Passport - Uganda', 'Visa - Umrah 2025'", max_length=200)),
                (
                    "document_number",
                    models.CharField(
                        blank=True, help_text="Passport number, visa number, etc.", max_length=100, null=True
                    ),
                ),
                (
                    "issuing_country",
                    models.CharField(blank=True, help_text="ISO 2-letter country code", max_length=2, null=True),
                ),
                ("file_public_id", models.CharField(help_text="Cloudinary public ID", max_length=160)),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="Optional: Direct URL (auto-generated from public_id)", null=True
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending Review"), ("VERIFIED", "Verified"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Internal staff notes", null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optional: Link document to a specific booking",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bookings.booking",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pilgrim",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.pilgrimprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optional: Link document to a specific trip (e.g., for visas)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trips.trip",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Staff member who uploaded (if admin upload)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Document",
                "verbose_name_plural": "historical Documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="HistoricalPassport",
        ),
        migrations.DeleteModel(
            name="HistoricalVisa",
        ),
        migrations.DeleteModel(
            name="Passport",
        ),
        migrations.DeleteModel(
            name="Visa",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["pilgrim", "document_type"], name="documents_pilgrim_b5e09b_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["trip"], name="documents_trip_id_e0843f_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="documents_status_f31a08_idx"),
        ),
    ]
