# Generated by Django 5.0.1 on 2025-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilgrims", "0003_migrate_to_unified_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_format",
            field=models.CharField(
                blank=True, help_text="File format/extension (jpg, pdf, png, etc.)", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="file_format",
            field=models.CharField(
                blank=True, help_text="File format/extension (jpg, pdf, png, etc.)", max_length=10, null=True
            ),
        ),
    ]
