# Generated by Django 5.0.1 on 2026-04-02 17:06

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_pilgrim_identity_fields"),
        ("bookings", "0006_remove_booking_currency_code_and_more"),
        ("pilgrims", "0004_add_file_format_to_document"),
        ("trips", "0007_historicaltrip_commercial_month_label_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPilgrimReadiness",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("profile_complete", models.BooleanField(default=False)),
                ("passport_valid", models.BooleanField(default=False)),
                ("visa_verified", models.BooleanField(default=False)),
                ("documents_complete", models.BooleanField(default=False)),
                ("payment_target_met", models.BooleanField(default=False)),
                ("payment_progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("ticket_issued", models.BooleanField(default=False)),
                ("darasa_one_completed", models.BooleanField(default=False)),
                ("darasa_two_completed", models.BooleanField(default=False)),
                ("send_off_completed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("READY_FOR_REVIEW", "Ready For Review"),
                            ("READY_FOR_TRAVEL", "Ready For Travel"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("ready_for_travel", models.BooleanField(default=False)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("blocking_reason", models.TextField(blank=True, default="")),
                ("validation_notes", models.TextField(blank=True, default="")),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bookings.booking",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trips.trippackage",
                    ),
                ),
                (
                    "pilgrim",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.pilgrimprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trips.trip",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pilgrim Readiness",
                "verbose_name_plural": "historical Pilgrim Readiness",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PilgrimReadiness",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("profile_complete", models.BooleanField(default=False)),
                ("passport_valid", models.BooleanField(default=False)),
                ("visa_verified", models.BooleanField(default=False)),
                ("documents_complete", models.BooleanField(default=False)),
                ("payment_target_met", models.BooleanField(default=False)),
                ("payment_progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("ticket_issued", models.BooleanField(default=False)),
                ("darasa_one_completed", models.BooleanField(default=False)),
                ("darasa_two_completed", models.BooleanField(default=False)),
                ("send_off_completed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("READY_FOR_REVIEW", "Ready For Review"),
                            ("READY_FOR_TRAVEL", "Ready For Travel"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("ready_for_travel", models.BooleanField(default=False)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("blocking_reason", models.TextField(blank=True, default="")),
                ("validation_notes", models.TextField(blank=True, default="")),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="readiness", to="bookings.booking"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilgrim_readiness",
                        to="trips.trippackage",
                    ),
                ),
                (
                    "pilgrim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_readiness",
                        to="accounts.pilgrimprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pilgrim_readiness", to="trips.trip"
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_pilgrim_readiness",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilgrim Readiness",
                "verbose_name_plural": "Pilgrim Readiness",
                "db_table": "pilgrim_readiness",
                "ordering": ["trip__start_date", "pilgrim__full_name", "created_at"],
                "indexes": [
                    models.Index(fields=["trip", "status"], name="pilgrim_rea_trip_id_f6150e_idx"),
                    models.Index(fields=["pilgrim", "status"], name="pilgrim_rea_pilgrim_f6301c_idx"),
                    models.Index(fields=["package"], name="pilgrim_rea_package_c5f093_idx"),
                    models.Index(fields=["ready_for_travel"], name="pilgrim_rea_ready_f_e0b188_idx"),
                ],
            },
        ),
    ]
