# Generated by Django 5.0.1 on 2026-04-02 23:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_pilgrim_identity_fields"),
        ("bookings", "0006_remove_booking_currency_code_and_more"),
        ("pilgrims", "0005_historicalpilgrimreadiness_pilgrimreadiness"),
        ("trips", "0007_historicaltrip_commercial_month_label_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("trip_updates", models.BooleanField(default=True)),
                ("document_updates", models.BooleanField(default=True)),
                ("readiness_updates", models.BooleanField(default=True)),
                ("daily_program_updates", models.BooleanField(default=True)),
                ("support_updates", models.BooleanField(default=True)),
                ("marketing_updates", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pilgrim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="accounts.pilgrimprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="DeviceInstallation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("installation_id", models.CharField(max_length=120, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("IOS", "iOS"), ("ANDROID", "Android"), ("WEB", "Web"), ("OTHER", "Other")],
                        max_length=12,
                    ),
                ),
                ("device_name", models.CharField(blank=True, default="", max_length=120)),
                ("device_model", models.CharField(blank=True, default="", max_length=120)),
                ("os_version", models.CharField(blank=True, default="", max_length=64)),
                ("app_version", models.CharField(blank=True, default="", max_length=32)),
                ("locale", models.CharField(blank=True, default="", max_length=32)),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("capability_flags", models.JSONField(blank=True, default=dict)),
                ("preference_state", models.JSONField(blank=True, default=dict)),
                ("provider_token_fields", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pilgrim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_installations",
                        to="accounts.pilgrimprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Installation",
                "verbose_name_plural": "Device Installations",
                "db_table": "device_installations",
                "ordering": ["-last_seen_at", "-updated_at"],
                "indexes": [
                    models.Index(fields=["pilgrim", "platform"], name="device_inst_pilgrim_plt_idx"),
                    models.Index(fields=["last_seen_at"], name="device_inst_last_seen_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TripFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")], default="DRAFT", max_length=12),
                ),
                ("overall_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("support_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("accommodation_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("transport_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("highlights", models.TextField(blank=True, default="")),
                ("improvements", models.TextField(blank=True, default="")),
                ("testimonial_opt_in", models.BooleanField(default=False)),
                ("follow_up_requested", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="bookings.booking",
                    ),
                ),
                (
                    "pilgrim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_feedback",
                        to="accounts.pilgrimprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_trip_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilgrim_feedback",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Feedback",
                "verbose_name_plural": "Trip Feedback",
                "db_table": "trip_feedback",
                "ordering": ["-submitted_at", "-updated_at"],
                "indexes": [
                    models.Index(fields=["trip", "status"], name="trip_feedback_trip_status_idx"),
                    models.Index(fields=["pilgrim", "status"], name="trip_feedback_pilgrim_st_idx"),
                ],
            },
        ),
    ]
