# Generated by Django 5.0.1 on 2025-10-20 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dua",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[("TAWAF", "Tawaf"), ("SAI", "Sai"), ("ARAFAT", "Arafat"), ("GENERAL", "General")],
                        max_length=12,
                    ),
                ),
                ("text_ar", models.TextField()),
                ("text_en", models.TextField(blank=True, null=True)),
                ("transliteration", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dua",
                "verbose_name_plural": "Duas",
                "db_table": "duas",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[("TRIP", "Trip"), ("PACKAGE", "Package"), ("USER", "User")], max_length=10
                    ),
                ),
                ("scope_id", models.UUIDField()),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("count_sent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
