# Generated by Django 5.0.1 on 2026-04-03

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidanceArticle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=120)),
                ("featured", models.BooleanField(default=False)),
                ("featured_order", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True, default="")),
                ("read_time", models.CharField(blank=True, default="", max_length=48)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("author_role_label", models.CharField(blank=True, default="", max_length=120)),
                ("intro", models.JSONField(blank=True, default=list)),
                ("sections", models.JSONField(blank=True, default=list)),
                ("takeaway", models.TextField(blank=True, default="")),
                ("sources", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guidance_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guidance Article",
                "verbose_name_plural": "Guidance Articles",
                "db_table": "guidance_articles",
                "ordering": ["-featured", "featured_order", "-published_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="guidancearticle",
            index=models.Index(fields=["slug"], name="guidance_art_slug_cf3d4f_idx"),
        ),
        migrations.AddIndex(
            model_name="guidancearticle",
            index=models.Index(fields=["category"], name="guidance_art_categor_6ab9ca_idx"),
        ),
        migrations.AddIndex(
            model_name="guidancearticle",
            index=models.Index(fields=["featured", "featured_order"], name="guidance_art_feature_58bf4e_idx"),
        ),
        migrations.AddIndex(
            model_name="guidancearticle",
            index=models.Index(fields=["published_at"], name="guidance_art_publish_23f8b4_idx"),
        ),
    ]
