# Generated by Django 5.0.1 on 2025-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="medical_conditions",
            field=models.TextField(blank=True, help_text="Medical conditions or special needs", null=True),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="medical_conditions",
            field=models.TextField(blank=True, help_text="Medical conditions or special needs", null=True),
        ),
    ]
