# Generated by Django 5.0.1 on 2025-10-30 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_historicalpilgrimprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Staff member who created this pilgrim",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="emergency_relationship",
            field=models.CharField(blank=True, help_text="Relationship to pilgrim", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="full_name",
            field=models.CharField(blank=True, help_text="Full name as on passport", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="passport_number",
            field=models.CharField(
                blank=True, db_index=True, help_text="Encrypted passport number", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalpilgrimprofile",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, help_text="Phone number for OTP verification", max_length=24, null=True
            ),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who created this pilgrim",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_pilgrims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="emergency_relationship",
            field=models.CharField(blank=True, help_text="Relationship to pilgrim", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="full_name",
            field=models.CharField(blank=True, help_text="Full name as on passport", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="passport_number",
            field=models.CharField(
                blank=True, db_index=True, help_text="Encrypted passport number", max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="pilgrimprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Phone number for OTP verification",
                max_length=24,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpilgrimprofile",
            name="dob",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AlterField(
            model_name="historicalpilgrimprofile",
            name="nationality",
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="pilgrimprofile",
            name="dob",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AlterField(
            model_name="pilgrimprofile",
            name="nationality",
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code", max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name="pilgrimprofile",
            index=models.Index(fields=["passport_number"], name="pilgrim_pro_passpor_2d07a1_idx"),
        ),
        migrations.AddIndex(
            model_name="pilgrimprofile",
            index=models.Index(fields=["phone"], name="pilgrim_pro_phone_a2abbb_idx"),
        ),
        migrations.AddIndex(
            model_name="pilgrimprofile",
            index=models.Index(fields=["full_name"], name="pilgrim_pro_full_na_5ccfca_idx"),
        ),
    ]
