# Generated by Django 5.0.1 on 2025-10-20 16:13

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=24, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("cities", models.JSONField(default=list)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")], default="PUBLIC", max_length=7
                    ),
                ),
                ("operator_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "db_table": "trips",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTrip",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("code", models.CharField(db_index=True, max_length=24)),
                ("name", models.CharField(max_length=120)),
                ("cities", models.JSONField(default=list)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")], default="PUBLIC", max_length=7
                    ),
                ),
                ("operator_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Trip",
                "verbose_name_plural": "historical Trips",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ItineraryItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("day_index", models.IntegerField(help_text="Day number (1-indexed)")),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, max_length=160, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("attach_public_id", models.CharField(blank=True, max_length=160, null=True)),
                ("attach_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="itinerary_items", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary Item",
                "verbose_name_plural": "Itinerary Items",
                "db_table": "itinerary_items",
                "ordering": ["day_index", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTripPackage",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=40)),
                ("price_minor_units", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")], default="PUBLIC", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Trip Package",
                "verbose_name_plural": "historical Trip Packages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=24)),
                ("hours", models.CharField(blank=True, help_text="e.g., 24/7, 9AM-5PM", max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emergency_contacts", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "db_table": "emergency_contacts",
            },
        ),
        migrations.CreateModel(
            name="TripFAQ",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="faqs", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip FAQ",
                "verbose_name_plural": "Trip FAQs",
                "db_table": "trip_faqs",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripGuideSection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("content_md", models.TextField(help_text="Markdown content")),
                ("attach_public_id", models.CharField(blank=True, max_length=160, null=True)),
                ("attach_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="guide_sections", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Guide Section",
                "verbose_name_plural": "Trip Guide Sections",
                "db_table": "trip_guide_sections",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TripPackage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("price_minor_units", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")], default="PUBLIC", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="packages", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Package",
                "verbose_name_plural": "Trip Packages",
                "db_table": "trip_packages",
            },
        ),
        migrations.CreateModel(
            name="PackageHotel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("address", models.TextField()),
                ("room_type", models.CharField(blank=True, max_length=60, null=True)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("group_confirmation_no", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hotels", to="trips.trippackage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Hotel",
                "verbose_name_plural": "Package Hotels",
                "db_table": "package_hotels",
                "ordering": ["check_in"],
            },
        ),
        migrations.CreateModel(
            name="PackageFlight",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "leg",
                    models.CharField(
                        choices=[("OUTBOUND", "Outbound"), ("RETURN", "Return"), ("OTHER", "Other")], max_length=10
                    ),
                ),
                ("carrier", models.CharField(max_length=8)),
                ("flight_no", models.CharField(max_length=12)),
                ("dep_airport", models.CharField(help_text="IATA code", max_length=3)),
                ("dep_dt", models.DateTimeField()),
                ("arr_airport", models.CharField(help_text="IATA code", max_length=3)),
                ("arr_dt", models.DateTimeField()),
                ("group_pnr", models.CharField(blank=True, max_length=16, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="flights", to="trips.trippackage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Flight",
                "verbose_name_plural": "Package Flights",
                "db_table": "package_flights",
                "ordering": ["dep_dt"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DOCS", "Documents"),
                            ("HEALTH", "Health"),
                            ("MONEY", "Money"),
                            ("PACKING", "Packing"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("link_url", models.URLField(blank=True, null=True)),
                ("attach_public_id", models.CharField(blank=True, max_length=160, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="checklist_items", to="trips.trip"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="trips.trippackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Item",
                "verbose_name_plural": "Checklist Items",
                "db_table": "checklist_items",
                "ordering": ["category", "label"],
            },
        ),
        migrations.CreateModel(
            name="TripUpdate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("body_md", models.TextField(help_text="Markdown content")),
                (
                    "urgency",
                    models.CharField(
                        choices=[("INFO", "Info"), ("IMPORTANT", "Important"), ("CRITICAL", "Critical")],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("publish_at", models.DateTimeField()),
                ("attach_public_id", models.CharField(blank=True, max_length=160, null=True)),
                ("attach_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="trips.trippackage",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Update",
                "verbose_name_plural": "Trip Updates",
                "db_table": "trip_updates",
                "ordering": ["-pinned", "-publish_at"],
            },
        ),
    ]
