# Generated by Django 5.0.1 on 2025-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrip",
            name="cover_image",
            field=models.URLField(blank=True, help_text="URL to cover image (Cloudinary)", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="cover_image",
            field=models.URLField(blank=True, help_text="URL to cover image (Cloudinary)", max_length=500, null=True),
        ),
    ]
