# Generated by Django 5.0.1 on 2025-11-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("trips", "0002_historicaltrip_cover_image_trip_cover_image"),
    ]

    operations = [
        # Rename existing currency field to currency_code
        migrations.RenameField(
            model_name="trippackage",
            old_name="currency",
            new_name="currency_code",
        ),
        migrations.RenameField(
            model_name="historicaltrippackage",
            old_name="currency",
            new_name="currency_code",
        ),
        # Add new FK field
        migrations.AddField(
            model_name="trippackage",
            name="currency_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="common.currency",
            ),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="currency_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.currency",
            ),
        ),
    ]
