# Generated by Django 5.0.1 on 2025-11-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_populate_and_migrate_currencies"),
        ("trips", "0003_historicaltrippackage_currency_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltrippackage",
            name="currency_code",
        ),
        migrations.RemoveField(
            model_name="historicaltrippackage",
            name="currency_fk",
        ),
        migrations.RemoveField(
            model_name="trippackage",
            name="currency_code",
        ),
        migrations.RemoveField(
            model_name="trippackage",
            name="currency_fk",
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.currency",
            ),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="common.currency",
            ),
        ),
    ]
