# Generated by Django 5.0.1 on 2025-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_remove_historicaltrippackage_currency_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrip",
            name="featured",
            field=models.BooleanField(default=False, help_text="Display trip prominently on app homepage"),
        ),
        migrations.AddField(
            model_name="trip",
            name="featured",
            field=models.BooleanField(default=False, help_text="Display trip prominently on app homepage"),
        ),
    ]
