# Generated by Django 5.0.1 on 2026-04-02 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_trip_public_metadata_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrip",
            name="commercial_month_label",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="historicaltrip",
            name="default_nights",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrip",
            name="family_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="historicaltrip",
            name="sales_open_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrip",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLANNING", "Planning"),
                    ("OPEN_FOR_SALES", "Open For Sales"),
                    ("PREPARATION", "Preparation"),
                    ("VISA_IN_PROGRESS", "Visa In Progress"),
                    ("TICKETING", "Ticketing"),
                    ("READY_TO_TRAVEL", "Ready To Travel"),
                    ("IN_JOURNEY", "In Journey"),
                    ("RETURNED", "Returned"),
                    ("POST_TRIP", "Post Trip"),
                    ("ARCHIVED", "Archived"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="airline_booking_month",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="end_date_override",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="hotel_booking_month",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="nights",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="package_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="sales_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="start_date_override",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltrippackage",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SELLING", "Selling"),
                    ("WAITLIST", "Waitlist"),
                    ("CLOSED", "Closed"),
                    ("IN_OPERATION", "In Operation"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="commercial_month_label",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="trip",
            name="default_nights",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="family_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="trip",
            name="sales_open_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLANNING", "Planning"),
                    ("OPEN_FOR_SALES", "Open For Sales"),
                    ("PREPARATION", "Preparation"),
                    ("VISA_IN_PROGRESS", "Visa In Progress"),
                    ("TICKETING", "Ticketing"),
                    ("READY_TO_TRAVEL", "Ready To Travel"),
                    ("IN_JOURNEY", "In Journey"),
                    ("RETURNED", "Returned"),
                    ("POST_TRIP", "Post Trip"),
                    ("ARCHIVED", "Archived"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="airline_booking_month",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="end_date_override",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="hotel_booking_month",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="nights",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="package_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="sales_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="start_date_override",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trippackage",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SELLING", "Selling"),
                    ("WAITLIST", "Waitlist"),
                    ("CLOSED", "Closed"),
                    ("IN_OPERATION", "In Operation"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TripMilestone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("HOTEL_CONTRACTED", "Hotel Contracted"),
                            ("AIRLINE_BLOCKED", "Airline Blocked"),
                            ("DOC_COLLECTION_OPEN", "Document Collection Open"),
                            ("DOC_VALIDATION_COMPLETE", "Document Validation Complete"),
                            ("DARASA_ONE", "Darasa One"),
                            ("DARASA_TWO", "Darasa Two"),
                            ("VISA_SUBMISSION", "Visa Submission"),
                            ("VISA_ISSUING", "Visa Issuing"),
                            ("PAYMENT_TARGET_90", "Payment Target 90"),
                            ("TICKETS_BOOKED", "Tickets Booked"),
                            ("TICKETS_ISSUED", "Tickets Issued"),
                            ("SEND_OFF_DINNER", "Send Off Dinner"),
                            ("TRAVEL_READY_PASS", "Travel Ready Pass"),
                            ("DEPARTURE_ASSEMBLY", "Departure Assembly"),
                            ("ARRIVAL_MADINAH", "Arrival Madinah"),
                            ("TRANSFER_MAKKAH", "Transfer Makkah"),
                            ("SECOND_UMRAH", "Second Umrah"),
                            ("RETURN_TRANSFER", "Return Transfer"),
                            ("ARRIVAL_HOME", "Arrival Home"),
                            ("POST_TRIP_SURVEY", "Post Trip Survey"),
                            ("POST_TRIP_CURRICULUM_START", "Post Trip Curriculum Start"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("SCHEDULED", "Scheduled"),
                            ("ON_TRACK", "On Track"),
                            ("AT_RISK", "At Risk"),
                            ("BLOCKED", "Blocked"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_public", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_trip_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="trips.trippackage",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="milestones", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Milestone",
                "verbose_name_plural": "Trip Milestones",
                "db_table": "trip_milestones",
                "ordering": ["target_date", "order", "created_at"],
                "indexes": [
                    models.Index(fields=["trip", "status"], name="trip_milest_trip_id_d8b37e_idx"),
                    models.Index(fields=["trip", "milestone_type"], name="trip_milest_trip_id_68db12_idx"),
                    models.Index(fields=["package"], name="trip_milest_package_89441e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TripResource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("UMRAH_GUIDE", "Umrah Guide"),
                            ("DUA_BOOKLET", "Dua Booklet"),
                            ("DAILY_PROGRAM", "Daily Program"),
                            ("CHECKLIST", "Checklist"),
                            ("POST_TRIP_MODULE", "Post Trip Module"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("file_public_id", models.CharField(max_length=160)),
                ("file_format", models.CharField(blank=True, max_length=10, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "viewer_mode",
                    models.CharField(
                        choices=[("VIEW_ONLY", "View Only"), ("DOWNLOADABLE", "Downloadable")],
                        default="VIEW_ONLY",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_pinned", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="trips.trippackage",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resources", to="trips.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Resource",
                "verbose_name_plural": "Trip Resources",
                "db_table": "trip_resources",
                "ordering": ["-is_pinned", "order", "title"],
                "indexes": [
                    models.Index(fields=["trip", "resource_type"], name="trip_resour_trip_id_47b4ba_idx"),
                    models.Index(fields=["package"], name="trip_resour_package_7d09ac_idx"),
                    models.Index(fields=["published_at"], name="trip_resour_publish_1e0b2e_idx"),
                ],
            },
        ),
    ]
