# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_historicaltrip_commercial_month_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrip",
            name="journey_type",
            field=models.CharField(
                choices=[("UMRAH", "Umrah"), ("HAJJ", "Hajj")],
                default="UMRAH",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="journey_type",
            field=models.CharField(
                choices=[("UMRAH", "Umrah"), ("HAJJ", "Hajj")],
                default="UMRAH",
                max_length=10,
            ),
        ),
    ]
